language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: bh/y84b8qtMusMsiJXrEOU/7hG7179tlPAPKZTUMUFdHXcg7tEFm4HU0xWx7BONV2sWwq/5P2qsaHlM/NyRLSXX/tYydGboJmoOW+Lh44dtul1yJguRCVCuZY8oR2/6zQ2CzyRjvfRrezF7P9l23TeroYe23mVmAy8fNjqWjW6nbzWgoIa3qdVPikEK+ylsB+rOyWoKBYT+1gDY7uUMjF7mcCIYNA9bAOTuQqzvTSPErqSkIJeIOdqrcLlvRFt2RuBHL9hC6UwZfE4nV1M6zFKJfWlMOo2WVu84RJ+tUn3yA1ZdkkFKYrn4rrFOggRoL38/fl8ssJlMI76pu0q55gtWnb0AV+rnvngWs2kbySOVleusNqg1ubXdOfo9e28R2F14lDLpeqv0OgCFpC1ggHTzG/fDFVvA1AAwnAFdcoB6X3xCtTs4l/c2Ol6+FGuW1+soFbFcmkp8CldAybuWiZvJLRrUYvGhBWczEe3KNo0DKA6A/MizygBUfddXCpkc9ljpczR+NSBKqQ5bTFmidZe6xYOJRdXTy2+6I5cV1HmknVTANuJMGSoCYF3SNh8O1DVKrOWBKPMbknwaTDbDqvZc2TJc5Pn+todb8eLuX/mXUrmbcsNDPBr21FY1LzOYZSmAEasFaoQobOHgNX+qkIfuLGupnD7dqsqDmj45Kzxk=
  app: shrouded-lake-21155
  on:
    repo: yh2n/shift-client
